language: python
python:
  - "3.8"
before_install:
  - pip install poetry
install:
  - poetry install -v
script:
  - true
deploy:
  provider: script
  script: poetry publish --build
  on:
    tags: true
    condition: "$TRAVIS_PYTHON_VERSION == 3.8"
