#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import sys
import time


def file_sequence(string):
    for char in string:
        if not char.isalnum():
            continue
        if char.isupper():
            yield 'capital'

        yield f'sounds/{char.lower()}.wav'


def main():
    for f in file_sequence(sys.argv[1]):
        os.system(f"aplay {f}")
        if f.endswith('capital.wav'):
            continue
        if len(sys.argv) > 2:
            time.sleep(float(sys.argv[2]))


if __name__ == '__main__':
    main()
