#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import sys
import time


def playsound(path):
    os.system(f"aplay {path}")


def to_letters(string):
    seq = []

    for char in string:
        if char.isalnum():
            if char.isupper():
                seq.append('capital')
            seq.append(char.lower())

    return seq


def to_files(letters):
    return [f'sounds/{elem}.wav' for elem in letters]


if __name__ == '__main__':
    for f in to_files(to_letters(sys.argv[1])):
        playsound(f)
        if f.endswith('capital.wav'):
            continue
        if len(sys.argv) > 2:
            time.sleep(float(sys.argv[2]))
